name: CI

on:
  push:
    paths-ignore:
      - "**/*.md"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v1

      - name: Install `wasm-pack`
        run: cargo install wasm-pack

      - name: Pre-Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Build
        run: wasm-pack build

      - name: Setup test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-run
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-wasm
          path: pkg

  build-www:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build-wasm]
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact 
        uses: actions/download-artifact@v3
        with:
          name: built-wasm
          path: www/src/lib

      - name: Setup Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm
          cache-dependency-path: "**/package-lock.json"

      - name: Install npm packages
        run: npm install --save-dev
        working-directory: www

      - name: Build
        run: npm run export
        working-directory: www

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-www
          path: www/dist
